name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root   # 如果是其他用户，改这里
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/final-project
            git pull origin main
            docker compose down
            docker compose up --build -d